import { Router } from "express";
import { authRoutes } from "./authRoutes";
import { fieldRoutes } from "./fieldRoutes";
import { masterControllerRoutes } from "./masterControllerRoutes";
import { zoneRoutes } from "./zoneRoutes";
import { valveRoutes } from "./valveRoutes";
import { commandRoutes } from "./commandRoutes";
import { deviceRoutes } from "./deviceRoutes";
import { scheduleRoutes } from "./scheduleRoutes";
import { productRoutes } from "./productRoutes";
import { orderRoutes } from "./orderRoutes";
import { servicePlanRoutes } from "./servicePlanRoutes";
import { supportTicketRoutes } from "./supportTicketRoutes";
import { adminRoutes } from "./adminRoutes";
import { userRoutes } from "./userRoutes";
import { inventoryRoutes } from "./inventoryRoutes";
import { reportRoutes } from "./reportRoutes";
import { settingsRoutes } from "./settingsRoutes";
import { slaveBoardRoutes } from "./slaveBoardRoutes";
import { farmerRoutes } from "./farmerRoutes";
import { irrigationRoutes } from "./irrigationRoutes";
import { monitoringRoutes } from "./monitoringRoutes";
import { dashboardRoutes } from "./dashboardRoutes";

export const apiRoutes = Router();

apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/fields", fieldRoutes);
apiRoutes.use("/masters", masterControllerRoutes);
apiRoutes.use("/", slaveBoardRoutes);
apiRoutes.use("/", zoneRoutes);
apiRoutes.use("/", valveRoutes);
apiRoutes.use("/commands", commandRoutes);
apiRoutes.use("/device", deviceRoutes);
apiRoutes.use("/schedules", scheduleRoutes);
apiRoutes.use("/products", productRoutes);
apiRoutes.use("/orders", orderRoutes);
apiRoutes.use("/servicePlans", servicePlanRoutes);
apiRoutes.use("/tickets", supportTicketRoutes);
apiRoutes.use("/admin", adminRoutes);
apiRoutes.use("/users", userRoutes);
apiRoutes.use("/inventory", inventoryRoutes);
apiRoutes.use("/reports", reportRoutes);
apiRoutes.use("/settings", settingsRoutes);
apiRoutes.use("/farmers", farmerRoutes);
apiRoutes.use("/irrigation", irrigationRoutes);
apiRoutes.use("/", monitoringRoutes);
apiRoutes.use("/dashboard", dashboardRoutes);
